configs:
  upnp_json:
    content: |
      {
        "port_forwards": [
          {
            "description": "first_whoami",
            "external_port": "8081",
            "protocol": "TCP"
          },
          {
            "description": "second_whoami",
            "internal_port": "8082",
            "external_port": "8080",
            "protocol": "TCP"
          }
        ]
      }
services:
  first_whoami:
    image: traefik/whoami
    ports:
      - "8081:80"
  second_whoami:
    image: traefik/whoami
    ports:
      - "8082:80"
  upnp-service:
    image: "dadangeuy/upnp-service:latest"
    configs:
      - source: upnp_json
        target: /etc/upnp-service/upnp.json
    network_mode: host # works while the container runs
    build:
      context: docker-image
      network: host # works during the build if needed
