#!/usr/bin/env bash

GATEWAY=$(ip route | head -1 | awk '{print $3}')
printf '%s\n' "Detected gateway is [$GATEWAY]"

LOCAL_IP=$(ip route | head -1 | awk '{print $9}')
printf '%s\n' "Detected local ip is [$LOCAL_IP]"

CONFIG="/etc/upnp-service/upnp.json"
LENGTH=$(jq ".port_forwards | length" $CONFIG)

for ((i = 0; i < LENGTH; i++)); do
  printf '%s\n' "Start updating UPnP entry with port redirections [$INTERNAL_PORT $EXTERNAL_PORT $PROTOCOL]"

  DESCRIPTION=$(jq -r ".port_forwards[$i].description" $CONFIG)
  INTERNAL_PORT=$(jq -r ".port_forwards[$i] | .internal_port // .external_port"  $CONFIG)
  EXTERNAL_PORT=$(jq -r ".port_forwards[$i].external_port" $CONFIG)
  PROTOCOL=$(jq -r ".port_forwards[$i].protocol" $CONFIG)

  if upnpc -l | grep -E "${PROTOCOL}[[:blank:]]+${EXTERNAL_PORT}->${LOCAL_IP}:${INTERNAL_PORT}"; then
    printf "%s\n" "UPnP entry exists, ignoring [$INTERNAL_PORT $EXTERNAL_PORT $PROTOCOL]"
  else
    printf "%s\n" "UPnP entry did not exists, updating [$INTERNAL_PORT $EXTERNAL_PORT $PROTOCOL]"
    
    printf "%s\n" "Deleting UPnP entry (if exists) [$EXTERNAL_PORT $PROTOCOL]"
    upnpc -f "$EXTERNAL_PORT" "$PROTOCOL"
    
    printf "%s\n" "Adding UPnP entry [$INTERNAL_PORT $EXTERNAL_PORT $PROTOCOL]"
    upnpc -e "$DESCRIPTION" -r "$INTERNAL_PORT" "$EXTERNAL_PORT" "$PROTOCOL"
  fi

  printf '%s\n' "Finish updating UPnP entry with port redirections [$INTERNAL_PORT $EXTERNAL_PORT $PROTOCOL]"
done
